version: '2'

services:
  server:
    build: ./
    container_name: go-app
    command: go run server.go
    environment:
      PORT: 8085
    ports:
      - "8085:8085"
    volumes:
      - .:/go/src/github.com/go-app

